using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Case.Lib
{
    public class DataService
    {
        public string[][] Res(string[] gender, string[] battlepass, string[] rase, string[] clas, string[] weapon, string[] armor)
        {
            

            Random rn = new Random((int)DateTime.Now.Ticks);
            string[] player1 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "3" };
            string[] player2 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "6" };
            string[] player3 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "9" };
            string[] player4 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "12" };
            string[] player5 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "15" };
            string[] player6 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "18" };
            string[] player7 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "21" };
            string[] player8 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "24" };
            string[] player9 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "27" };
            string[] player10 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "30" };
            string[] player11 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "33" };
            string[] player12 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "36" };
            string[] player13 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "39" };
            string[] player14 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "42" };
            string[] player15 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "45" };
            string[] player16 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "48" };
            string[] player17 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "51" };
            string[] player18 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "54" };
            string[] player19 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "57" };
            string[] player20 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "60" };
            string[] player21 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "63" };
            string[] player22 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "66" };
            string[] player23 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "69" };
            string[] player24 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "72" };
            string[] player25 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "75" };
            string[] player26 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "78" };
            string[] player27 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "81" };
            string[] player28 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "84" };
            string[] player29 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "87" };
            string[] player30 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "90" };
            string[] player31 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "93" };
            string[] player32 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "96" };
            string[] player33 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "99" };
            string[] player34 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "2" };
            string[] player35 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "5" };
            string[] player36 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "8" };
            string[] player37 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "11" };
            string[] player38 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "14" };
            string[] player39 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "17" };
            string[] player40 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "20" };
            string[] player41 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "23" };
            string[] player42 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "26" };
            string[] player43 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "29" };
            string[] player44 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "32" };
            string[] player45 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "35" };
            string[] player46 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "38" };
            string[] player47 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "41" };
            string[] player48 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "44" };
            string[] player49 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "47" };
            string[] player50 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "50" };
            string[] player51 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "53" };
            string[] player52 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "56"};
            string[] player53 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "59" };
            string[] player54 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "62" };
            string[] player55 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "1" };
            string[] player56 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "1" };
            string[] player57 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "1" };
            string[] player58 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "1" };
            string[] player59 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "1" };
            string[] player60 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "1" };
            string[] player61 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "1" };
            string[] player62 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "1" };
            string[] player63 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "1" };
            string[] player64 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "1" };
            string[] player65 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "1" };
            string[] player66 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "1" };
            string[] player67 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "1" };
            string[] player68 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], "1" };
            string[] player69 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], Convert.ToString(rn.Next(1, 101)) };
            string[] player70 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], Convert.ToString(rn.Next(1, 101)) };
            string[] player71 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], Convert.ToString(rn.Next(1, 101)) };
            string[] player72 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], Convert.ToString(rn.Next(1, 101)) };
            string[] player73 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], Convert.ToString(rn.Next(1, 101)) };
            string[] player74 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], Convert.ToString(rn.Next(1, 101)) };
            string[] player75 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], Convert.ToString(rn.Next(1, 101)) };
            string[] player76 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], Convert.ToString(rn.Next(1, 101)) };
            string[] player77 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], Convert.ToString(rn.Next(1, 101)) };
            string[] player78 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], Convert.ToString(rn.Next(1, 101)) };
            string[] player79 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], Convert.ToString(rn.Next(1, 101)) };
            string[] player80 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], Convert.ToString(rn.Next(1, 101)) };
            string[] player81 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], Convert.ToString(rn.Next(1, 101)) };
            string[] player82 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], Convert.ToString(rn.Next(1, 101)) };
            string[] player83 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], Convert.ToString(rn.Next(1, 101)) };
            string[] player84 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], Convert.ToString(rn.Next(1, 101)) };
            string[] player85 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], Convert.ToString(rn.Next(1, 101)) };
            string[] player86 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], Convert.ToString(rn.Next(1, 101)) };
            string[] player87 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], Convert.ToString(rn.Next(1, 101)) };
            string[] player88 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], Convert.ToString(rn.Next(1, 101)) };
            string[] player89 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], Convert.ToString(rn.Next(1, 101)) };
            string[] player90 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], Convert.ToString(rn.Next(1, 101)) };
            string[] player91 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], Convert.ToString(rn.Next(1, 101)) };
            string[] player92 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], Convert.ToString(rn.Next(1, 101)) };
            string[] player93 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], Convert.ToString(rn.Next(1, 101)) };
            string[] player94 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], Convert.ToString(rn.Next(1, 101)) };
            string[] player95 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], Convert.ToString(rn.Next(1, 101)) };
            string[] player96 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], Convert.ToString(rn.Next(1, 101)) };
            string[] player97 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], Convert.ToString(rn.Next(1, 101)) };
            string[] player98 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], Convert.ToString(rn.Next(1, 101)) };
            string[] player99 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], Convert.ToString(rn.Next(1, 101)) };
            string[] player100 = new string[] { gender[rn.Next(0, gender.Length)], battlepass[rn.Next(0, battlepass.Length)], rase[rn.Next(0, rase.Length)], clas[rn.Next(0, clas.Length)], weapon[rn.Next(0, weapon.Length)], armor[rn.Next(0, armor.Length)], Convert.ToString(rn.Next(1, 101)) };

            string[][] result = new string[][] { player1, player2, player3, player4, player5, player6, player7, player8, player9, player10, player11, player12, player13, player14, player15, player16, player17, player18, player19, player20, player21, player22, player23, player24, player25, player26, player27, player28, player29, player30, player31, player32, player33, player34, player35, player36, player37, player38, player39, player40, player41, player42, player43, player44, player45, player46, player47, player48, player49, player50, player51, player52, player53, player54, player55, player56, player57, player58, player59, player60, player61, player62, player63, player64, player65, player66, player67, player68, player69, player70, player71, player72, player73, player74, player75, player76, player77, player78, player79, player80, player81, player82, player83, player84, player85, player86, player87, player88, player89, player90, player91, player92, player93, player94, player95, player96, player97, player98, player99, player100 };

            return result;
        }
    }
}
